### ISSUE TITLE
vsphere-csi-driver refresh to latest version

### ISSUE THREAD

**Issue by gauravAggrahari** [IBM/ibm-satellite-storage#284] opened 2023-02-02 09:47 UTC

**Comment by gauravAggrahari** [comment] 2023-02-02 09:48
The current version of the vsphere-csi-drvier is 2.5.1 which is not compatible with ROKS 4.11 onwards. We need to refresh the template to the latest version of the CSI driver

**Comment by gauravAggrhari** [comment] 2023-04-13 05:11
PR is merged.
@asifdxtreme Please update the test results here.
Thank you.

**Comment by asifdxtreme** [comment] 2023-04-13 05:15
@aggarwalta Please update the VDO Test results once it's done.

**Comment by aggarwalta** [comment] 2023-04-14 06:03
From kubernetes 1.24 onwards, the label 'node-role.kubernetes.io/master' is no longer added to control plane nodes, only the label 'node-role.kubernetes.io/control-plane' will be added. 
The openshift cluster nodes were missing this label. Tested adding this label to all the control plane nodes, the pods are in Running state now. 

Command used: 
_kubectl label nodes <node_name> node-role.kubernetes.io/control-plane=_

Output:
<img width="1625" alt="Screenshot 2023-04-14 at 11 22 47 AM" src="https://user-images.githubusercontent.com/88435310/231954332-5483c9ee-7692-4f07-b0d6-ed8c8004d998.png">

**Comment by gauravAggrhari** [comment] 2023-04-14 06:19
@aggarwalta , @asifdxtreme ,
Thank you so much for your effort.
I see that one pod is still in `ContainerCreating` state. Can you please check that?
<img width="808" alt="image" src="https://user-images.githubusercontent.com/19754677/231955614-218fb278-2c98-4d99-9ba9-053ad97f9717.png">


 - As a part of the testing, can you please also create a PVC and try to mount that on a sample workload then perform some I/O on the volume.
 - Delete the workload and PVC you created.
- Next please delete the assignment and check if all the resources created by the template in `vmware-system-csi` and `vmware-system-vdo` are cleaned up.

I appreciate the efforts.
Thank you.

Regards,
Gaurav

**Comment by gauravAggrhari** [comment] 2023-04-17 05:12
@asifdxtreme , @aggarwalta ,
Any updates?

Regards,
Gaurav

**Comment by asifdxtreme** [comment] 2023-04-17 05:17
Webhook validation needs the CA_BUNDLE which we are missing currently, we have raised this issue with CSI folks to get help on this

**Comment by gauravAggrhari** [comment] 2023-04-17 06:28
@asifdxtreme ,
Do we have an ETA for this?

**Comment by gauravAggrhari** [comment] 2023-04-18 14:08
@aggarwalta , @asifdxtreme ,
Any updates on the above issue?

Regards,
Gaurav

**Comment by asifdxtreme** [comment] 2023-04-18 14:16
@gauravAggrahari We are checking this issue with CSI folks, we will try to close it by tomorrow .
/cc @aggarwalta

**Comment by gauravAggrhari** [comment] 2023-04-18 14:17
Sure. Thank you.

**Comment by gauravAggrhari** [comment] 2023-04-19 15:15
Hi, @asifdxtreme/@aggarwalta ,
Is there any update from CSI team?

cc: @nkkashyap , @sandaymin123 , @mssachan 

Regards,
Gaurav

**Comment by gauravAggrhari** [comment] 2023-04-19 15:23
Hi @asifdxtreme ,
Why is this label `node-role.kubernetes.io/control-plane` needed ? 
Is it possible to work without this label?

Regards,
Gaurav

**Comment by asifdxtreme** [comment] 2023-04-20 05:39
The label `node-role.kubernetes.io/master` was deprecated in 1.24 onwards, please see the below PR for more details
https://github.com/kubernetes/kubernetes/pull/107533

**Comment by gauravAggrhari** [comment] 2023-04-20 05:43
Thank you. @asifdxtreme. 
Is there any update on the CSI_BUNDLE issue ?

**Comment by asifdxtreme** [comment] 2023-04-20 11:04
@gauravAggrahari We need to execute this additional script before applying the CSI deployment yamls, we will be adding this as a part of pre-requisite in our VDO code, we will update the docker image soon with these changes.

**Comment by gauravAggrhari** [comment] 2023-04-24 05:19
Hi @asifdxtreme ,
Is there any update?

**Comment by asifdxtreme** [comment] 2023-04-26 09:35
VDO is working fine when deploying the CSI locally with webhook validation in kind cluster, but we try to deploy the same in openshift we get an error for certificate validation, currently we are using self signed certificate and it works fine in local cluster, but doesn't works in Openshift.

We need to find a way to get the organization signed certificate and use the same in webhook validation.
```
'kind.group: "StorageClass.storage.k8s.io/v1"
          name: "sat-vsphere-vsan-block" statusCode: "500 message: Internal error
          occurred: failed calling webhook "validation.csi.vsphere.vmware.com": failed
          to call webhook: Post "[https://vsphere-webhook-svc.vmware-system-csi.svc:443/validate?timeout=10s](https://vsphere-webhook-svc.vmware-system-csi.svc/validate?timeout=10s)":
          x509: certificate signed by unknown authority (possibly because of "x509:
          cannot verify signature: insecure algorithm SHA1-RSA (temporarily override
          with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate
          "vSphere CSI Admission Controller Webhook CA")"'
```

**Comment by gauravAggrhari** [comment] 2023-05-02 16:02
A new version of VDO docker image is released to address the above issues by VMware team which is updated in the template. Below is the PR
https://github.com/IBM/ibm-satellite-storage/pull/329

**Comment by gauravAggrhari** [comment] 2023-05-09 07:08
Hi @asifdxtreme,
New changes have been rolled out. It is available for testing.

**Comment by gauravAggrhari** [comment] 2023-05-09 14:40
@asifdxtreme to update deployment to get rid of this label `node-role.kubernetes.io/control-plane` for IBM's case.

**Comment by gauravAggrhari** [comment] 2023-05-11 07:03
Hi @asifdxtreme ,
Do we have any updates on the test?

**Comment by gauravAggrhari** [comment] 2023-05-19 04:57
Hi @asifdxtreme ,
As I informed, the changes have been rolled out to prod. Can we please have an update on the testing?

**Comment by aggarwalta** [comment] 2023-05-19 10:42
Hi @gauravAggrahari 

We are able to get all the pods in running state
<img width="1511" alt="Screenshot 2023-05-19 at 2 30 06 PM" src="https://github.com/IBM/ibm-satellite-storage/assets/88435310/0f3331f4-48d9-4f1b-b249-97d11f994af0">

But we are not able to get storageclass resource, hence we checked the csi-webhook pod.
On describing the csi-webhook pod, we are getting the following error 

`
{"level":"info","time":"2023-05-19T09:37:05.698875689Z","caller":"admissionhandler/admissionhandler.go:186","msg":"Webhook server started","TraceId":"b395ff6f-6314-4ddc-af61-d8c68e4c416b"}
{"level":"info","time":"2023-05-19T09:37:05.701485062Z","caller":"k8sorchestrator/k8sorchestrator.go:597","msg":"configMapAdded: Internal feature state values from \"internal-feature-states.csi.vsphere.vmware.com\" stored successfully: map[async-query-volume:true block-volume-snapshot:true cnsmgr-suspend-create-volume:true csi-auth-check:true csi-migration:true csi-windows-support:false improved-csi-idempotency:true improved-volume-topology:true list-volumes:false max-pvscsi-targets-per-vm:true online-volume-extend:true pv-to-backingdiskobjectid-mapping:false topology-preferential-datastores:true trigger-csi-fullsync:false use-csinode-id:true]","TraceId":"532223ca-55a4-46a9-b2fa-9277c4013676"}

2023/05/19 09:40:52 http: TLS handshake error from 172.30.88.213:51300: remote error: tls: bad certificate

2023/05/19 09:45:52 http: TLS handshake error from 172.30.88.213:48176: remote error: tls: bad certificate

2023/05/19 09:50:52 http: TLS handshake error from 172.30.88.213:49914: remote error: tls: bad certificate`

**Comment by gauravAggrhari** [comment] 2023-05-19 11:25
Hi @aggarwalta ,
Do you need to consult CSI driver team for this?

**Comment by gauravAggrhari** [comment] 2023-05-24 08:45
Hi @aggarwalta , @asifdxtreme ,
Do we have any updates on the issue?

**Comment by gauravAggrhari** [comment] 2023-05-26 06:06
Hi @asifdxtreme , @aggarwalta ,
Can you please provide some update on this?

Thank you.
Regards,
Gaurav

**Comment by asifdxtreme** [comment] 2023-05-29 08:16
Hi @gauravAggrahari ,
Thank you for your patience, We will be releasing a new patch version for VDO by 31st May.
/cc @lgayatri

**Comment by gauravAggrhari** [comment] 2023-06-01 05:27
Hi @asifdxtreme , @aggarwalta ,
Can you please provide an update on new VDO image?

Regards,
Gaurav

**Comment by gauravAggrhari** [comment] 2023-06-05 04:52
Hi @asifdxtreme , @aggarwalta,
Do we have any updates on the issue?

Regards,
Gaurav

**Comment by asifdxtreme** [comment] 2023-07-24 05:23
We need to use this repo https://github.com/openshift/vmware-vsphere-csi-driver-operator for deploying the validating webhook yaml.

The problem is that this repo is neither owned and managed by IBM/VMware, Openshift owns this repo and manages the update of CSI driver.

We need to take a call if IBM is okay for using other repo for deployment which is not managed by us.

**Comment by asifdxtreme** [comment] 2023-07-24 13:36
The Issue has been resolved, env has been updated with the changes, please find the working logs
```smohammadasi@smohammada2MD6R ~ % k get pvc pvc -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
    volume.kubernetes.io/selected-node: vm07
    volume.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
  creationTimestamp: "2023-07-24T13:20:29Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc
  namespace: default
  resourceVersion: "79572253"
  uid: 718d3d37-82b9-4acd-adb6-6803531cacf2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sat-vsphere-vsan-block-metro
  volumeMode: Filesystem
  volumeName: pvc-718d3d37-82b9-4acd-adb6-6803531cacf2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
smohammadasi@smohammada2MD6R ~ % k get pods
NAME      READY   STATUS    RESTARTS   AGE
app-pod   1/1     Running   0          83d
smohammadasi@smohammada2MD6R ~ % k logs -n vmware-system-csi vmware-vsphere-csi-driver-webhook-55c9b55bc8-r5mw7
{"level":"info","time":"2023-07-24T13:11:01.264395384Z","caller":"logger/logger.go:41","msg":"Setting default log level to :\"PRODUCTION\""}
{"level":"info","time":"2023-07-24T13:11:01.264518299Z","caller":"syncer/main.go:76","msg":"Version : v2.7.0","TraceId":"73c8f61d-a531-4e5d-9466-ff21969a556a"}
{"level":"info","time":"2023-07-24T13:11:01.264550231Z","caller":"syncer/main.go:88","msg":"Starting container with operation mode: WEBHOOK_SERVER","TraceId":"73c8f61d-a531-4e5d-9466-ff21969a556a"}
{"level":"info","time":"2023-07-24T13:11:01.2645629Z","caller":"k8sorchestrator/k8sorchestrator.go:244","msg":"Initializing k8sOrchestratorInstance","TraceId":"73c8f61d-a531-4e5d-9466-ff21969a556a"}
{"level":"info","time":"2023-07-24T13:11:01.264598977Z","caller":"kubernetes/kubernetes.go:85","msg":"k8s client using in-cluster config","TraceId":"73c8f61d-a531-4e5d-9466-ff21969a556a"}
{"level":"info","time":"2023-07-24T13:11:01.264796605Z","caller":"kubernetes/kubernetes.go:389","msg":"Setting client QPS to 100.000000 and Burst to 100.","TraceId":"73c8f61d-a531-4e5d-9466-ff21969a556a"}
{"level":"info","time":"2023-07-24T13:11:01.265165891Z","caller":"kubernetes/kubernetes.go:85","msg":"k8s client using in-cluster config","TraceId":"73c8f61d-a531-4e5d-9466-ff21969a556a"}
{"level":"info","time":"2023-07-24T13:11:01.266102039Z","caller":"kubernetes/kubernetes.go:389","msg":"Setting client QPS to 100.000000 and Burst to 100.","TraceId":"73c8f61d-a531-4e5d-9466-ff21969a556a"}
{"level":"info","time":"2023-07-24T13:11:01.27468818Z","caller":"k8sorchestrator/k8sorchestrator.go:371","msg":"New internal feature states values stored successfully: map[async-query-volume:true block-volume-snapshot:true cnsmgr-suspend-create-volume:true csi-auth-check:true csi-migration:true csi-windows-support:false improved-csi-idempotency:true improved-volume-topology:true list-volumes:false max-pvscsi-targets-per-vm:true online-volume-extend:true pv-to-backingdiskobjectid-mapping:false topology-preferential-datastores:true trigger-csi-fullsync:false use-csinode-id:true]","TraceId":"73c8f61d-a531-4e5d-9466-ff21969a556a"}
{"level":"info","time":"2023-07-24T13:11:01.274777276Z","caller":"k8sorchestrator/k8sorchestrator.go:291","msg":"k8sOrchestratorInstance initialized","TraceId":"73c8f61d-a531-4e5d-9466-ff21969a556a"}
{"level":"info","time":"2023-07-24T13:11:01.275115565Z","caller":"admissionhandler/admissionhandler.go:186","msg":"Webhook server started","TraceId":"73c8f61d-a531-4e5d-9466-ff21969a556a"}
{"level":"info","time":"2023-07-24T13:11:01.277228522Z","caller":"k8sorchestrator/k8sorchestrator.go:597","msg":"configMapAdded: Internal feature state values from \"internal-feature-states.csi.vsphere.vmware.com\" stored successfully: map[async-query-volume:true block-volume-snapshot:true cnsmgr-suspend-create-volume:true csi-auth-check:true csi-migration:true csi-windows-support:false improved-csi-idempotency:true improved-volume-topology:true list-volumes:false max-pvscsi-targets-per-vm:true online-volume-extend:true pv-to-backingdiskobjectid-mapping:false topology-preferential-datastores:true trigger-csi-fullsync:false use-csinode-id:true]","TraceId":"e1e4aee0-d60a-48d8-b103-d70fe8027d4c"}
{"level":"info","time":"2023-07-24T13:15:46.092130533Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-block\"","TraceId":"c9d28a51-4589-427c-bbab-e83c64af61a2"}
{"level":"info","time":"2023-07-24T13:15:46.09233712Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-block\" Passed","TraceId":"c9d28a51-4589-427c-bbab-e83c64af61a2"}
{"level":"info","time":"2023-07-24T13:15:46.325230749Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-block-metro\"","TraceId":"ce334d37-c454-4441-8cae-f4791e3d7bde"}
{"level":"info","time":"2023-07-24T13:15:46.325263923Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-block-metro\" Passed","TraceId":"ce334d37-c454-4441-8cae-f4791e3d7bde"}
{"level":"info","time":"2023-07-24T13:15:46.552718684Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-file\"","TraceId":"370eda03-c85e-42cb-87f1-d175167054d5"}
{"level":"info","time":"2023-07-24T13:15:46.552780768Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-file\" Passed","TraceId":"370eda03-c85e-42cb-87f1-d175167054d5"}
{"level":"info","time":"2023-07-24T13:15:46.774022552Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-file-metro\"","TraceId":"f4f363d9-99cf-4598-87bf-065b431398b3"}
{"level":"info","time":"2023-07-24T13:15:46.774100817Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-file-metro\" Passed","TraceId":"f4f363d9-99cf-4598-87bf-065b431398b3"}
{"level":"info","time":"2023-07-24T13:20:46.217046326Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-block\"","TraceId":"c61a1d5e-5ec6-4cb1-9434-53dd6c30b970"}
{"level":"info","time":"2023-07-24T13:20:46.217108861Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-block\" Passed","TraceId":"c61a1d5e-5ec6-4cb1-9434-53dd6c30b970"}
{"level":"info","time":"2023-07-24T13:20:46.4300471Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-block-metro\"","TraceId":"a87af481-d6c5-4ec4-a274-e404174e3d55"}
{"level":"info","time":"2023-07-24T13:20:46.430087633Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-block-metro\" Passed","TraceId":"a87af481-d6c5-4ec4-a274-e404174e3d55"}
{"level":"info","time":"2023-07-24T13:20:46.586689131Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-file\"","TraceId":"4502f6cf-6278-4200-af16-35af7916d4af"}
{"level":"info","time":"2023-07-24T13:20:46.586719167Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-file\" Passed","TraceId":"4502f6cf-6278-4200-af16-35af7916d4af"}
{"level":"info","time":"2023-07-24T13:20:46.765797058Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-file-metro\"","TraceId":"2cc3cc04-e036-417b-ba1a-1eb4d348038b"}
{"level":"info","time":"2023-07-24T13:20:46.765826522Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-file-metro\" Passed","TraceId":"2cc3cc04-e036-417b-ba1a-1eb4d348038b"}
{"level":"info","time":"2023-07-24T13:25:45.552998762Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-block\"","TraceId":"bf8d03bd-f10f-468d-9ecf-3de411035c42"}
{"level":"info","time":"2023-07-24T13:25:45.5530613Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-block\" Passed","TraceId":"bf8d03bd-f10f-468d-9ecf-3de411035c42"}
{"level":"info","time":"2023-07-24T13:25:45.760158615Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-block-metro\"","TraceId":"4035be77-7501-46a8-8f19-d5ded643f943"}
{"level":"info","time":"2023-07-24T13:25:45.760300153Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-block-metro\" Passed","TraceId":"4035be77-7501-46a8-8f19-d5ded643f943"}
{"level":"info","time":"2023-07-24T13:25:45.917970656Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-file\"","TraceId":"df8d0d05-6849-491f-967b-78ffeffec03b"}
{"level":"info","time":"2023-07-24T13:25:45.918081197Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-file\" Passed","TraceId":"df8d0d05-6849-491f-967b-78ffeffec03b"}
{"level":"info","time":"2023-07-24T13:25:46.075178525Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-file-metro\"","TraceId":"8e8211ad-f99e-452a-bc56-7e9835fe077d"}
{"level":"info","time":"2023-07-24T13:25:46.075237637Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-file-metro\" Passed","TraceId":"8e8211ad-f99e-452a-bc56-7e9835fe077d"}
{"level":"info","time":"2023-07-24T13:30:45.46033134Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-block\"","TraceId":"57da0e39-dbcf-42eb-a194-765336f0a99a"}
{"level":"info","time":"2023-07-24T13:30:45.4603662Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-block\" Passed","TraceId":"57da0e39-dbcf-42eb-a194-765336f0a99a"}
{"level":"info","time":"2023-07-24T13:30:45.624510522Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-block-metro\"","TraceId":"6fc2a5c3-252f-41b3-983a-eb08d572629b"}
{"level":"info","time":"2023-07-24T13:30:45.624590081Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-block-metro\" Passed","TraceId":"6fc2a5c3-252f-41b3-983a-eb08d572629b"}
{"level":"info","time":"2023-07-24T13:30:45.808080102Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-file\"","TraceId":"57cbcb34-2527-4baf-a046-76da2fe922ee"}
{"level":"info","time":"2023-07-24T13:30:45.808152001Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-file\" Passed","TraceId":"57cbcb34-2527-4baf-a046-76da2fe922ee"}
{"level":"info","time":"2023-07-24T13:30:45.993940928Z","caller":"admissionhandler/validatestorageclass.go:77","msg":"Validating StorageClass: \"sat-vsphere-vsan-file-metro\"","TraceId":"2b79acf5-28d3-44c5-8df5-d33b3cc03509"}
{"level":"info","time":"2023-07-24T13:30:45.994150416Z","caller":"admissionhandler/validatestorageclass.go:99","msg":"Validation of StorageClass: \"sat-vsphere-vsan-file-metro\" Passed","TraceId":"2b79acf5-28d3-44c5-8df5-d33b3cc03509"}
```
/cc @lgayatri

**Closed as completed** 2024-03-26 14:48 UTC
